package ahmed.test.monolithic.monolithic_mod.shared.domain.model;

import java.util.List;

/**
 * Base Business Rules Infs
 * All classes will be automatically Bean generated By Spring boot
 * Refer To RulesConfig
 * @param <T>
 * @param <C>
 * @param <U>
 */
public interface IBaseBusinessRules<T extends DomainModel,
        C extends List<? extends AppMessage>, U extends User> {
    public boolean isNotValid(T i, User user);

    public List<AppMessage> addMessage(T i, User userDTO);

    public String getBusinessRuleCode();
}